### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by briggySmalls** [rasoolsomji/django-security#1]
I am not very django-savvy, so forgive me if the following is obvious:

I am unsure how this repo is to be used? Are the python files here django apps?

Maybe you could consider a section in the README indicating how people can use this repo?

**Comment by rasoolsomji** [comment]
Thanks for the feedback!

This isn't really an app or to be run in any way, it is just a collection of common cybersecurity vulnerabilities and gotchas I've come across working on different projects that I wanted to keep track of in one place - with possible solutions.  I'll add an introduction explaining this, thanks for pointing this out!

**Comment by briggySmalls** [comment]
Tidy ✌️
